# Generated by Django 2.0.8 on 2018-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='length',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='size',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='start_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='Otpravitel',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Poluchatel',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='kolichestvo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='obem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='upakovka',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='zakazchik',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
